#! /bin/bash

<<comment
Prerequisites:
-This script was tested on a new Mint21 machine and Ubuntu 20.04

Description:
-This script clones all repos needed to build an Azure image for the WLSOM (SAMA5 MPU) into the newly created directory
-The script copies bblayers.conf, local.conf and defconfig into proper folders for building correctly
-The script copies rebuild script into the build folder, so the image can be rebuilt by just running this script as ". t1s.rebuild" from the build folder
-The script also puts t1s.clean, t1s.rebuild, and sdk scripts into the build folder
-Lastly it builds the final image


Usage:
". wlsom-t1s-build"

Examples:
For new installs use the following command with the script in your created build folder:
". wlsom-t1s-build"
This will clone all repos and build an WLSOM t1s image

To build only, after you have already setup, run:
". t1s.rebuild" from the build directory

 Written by:
 __  __     
/\ \/ /     
\ \  _"-.  
 \ \_\ \_\  
  \/_/\/_/ 

  
comment

rd='\e[0;31m'
lg='\e[1;32m'
lp='\e[1;35m'
cy='\e[0;36m'
NC='\e[0m'

#--------------START WORK--------------------
sudo apt-get update
sudo apt-get -y upgrade

sudo apt-get -y install gawk wget git git-lfs diffstat unzip texinfo gcc-multilib \
     build-essential chrpath socat cpio python3 python3-pip python3-pexpect \
     xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev \
     pylint xterm libssl-dev python3-pyasyncore

export CROSS_COMPILE=arm-linux-gnueabi-

echo -e "${rd}-----Cloning Microchip Repos-----${NC}"
git clone https://github.com/k-mchp/meta-microchip-wlsom-t1s.git
git clone https://git.yoctoproject.org/poky -b dunfell
git clone https://git.openembedded.org/meta-openembedded -b dunfell
git clone https://github.com/linux4sam/meta-atmel.git -b dunfell

echo -e "${lg}-----Building t1s Image for WLSOM-----${NC}"
cd poky
export TEMPLATECONF=${TEMPLATECONF:-../meta-atmel/conf}
source oe-init-build-env build-microchip
cp -r -f -v ../../t1s.bblayers.conf conf/bblayers.conf
cp -r -f -v ../../t1s.local.conf conf/local.conf
MACHINE=sama5d27-wlsom1-ek-sd bitbake wlsom-t1s-demo

cd ../..
echo -e "${lp}T1s Build Complete!!! ${NC}\c"
echo -e "\c"

